# 히든레이어

- 보스턴 집값 예측: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv

- 아이리스 품종 분류: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv 

- Hidden layer: 기존의 퍼셉트론's input layer & output layer 사이에 추가된 new 레이어, 노드로 구성 <br>
hidden layer의 모든 값을 입력으로 받아 new 출력을 만드는 new 퍼셉트론 생성<br>
hidden layer's 노드 수 == new 퍼셉트론's 수 == 해당 모델's 독립변수 개수<br>

이렇게 복수 개의 model이 연결된 것이 ``인공신경망``

## 0. Tensorflow & Pandas 라이브러리 사용

In [1]:
import tensorflow as tf
import pandas as pd

## 1. 보스턴 집값 예측
***
## 1-1. 과거의 데이터 준비

In [2]:
file_route = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
boston = pd.read_csv(file_route)

# 종속변수, 독립변수
inde_var = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
de_var = boston[['medv']]

print(inde_var.shape, de_var.shape)

(506, 13) (506, 1)


## 1-2. 모델 구조 생성

In [3]:
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X) #히든레이어 정의. 활성화 함수 = swish. 히든레이어 개수 ↑수록 모델's 정확도 ↑
Y = tf.keras.layers.Dense(1)(H) #입력 패러미터: H, X면 히든레이어 안 써먹는거
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

### 모델 구조 확인(학습 전 확인 권장)

In [4]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                140       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


## 1-3.데이터로 모델 학습(FIT)

In [8]:
model.fit(inde_var, de_var, epochs=10000, verbose=0)
model.fit(inde_var, de_var, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 11.5281
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 11.5140
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 10.6428
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 11.1484
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 11.2872
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 11.1666
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 10.6787
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 11.2799
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 11.3521
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 10.6667


## 1-4. 모델 이용하여 예측

In [9]:
print(model.predict(inde_var[:5]))
print(de_var[:5])

[[28.59684 ]
 [20.804296]
 [32.99336 ]
 [32.22288 ]
 [30.519676]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


*******

## 2. 아이리스 품종 분류
******
## 2-1. 과거의 데이터 준비


In [10]:
file_route = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(file_route)

## 2-2. 원핫인코딩

In [11]:
iris = pd.get_dummies(iris)

## 2-3. 독립변수, 종속변수 분리

In [13]:
inde_var = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
de_var = iris[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(inde_var.shape, de_var.shape)

(150, 4) (150, 3)


## 2-4. 모델 구조 생성

In [14]:
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X) #히든레이어 3중
H = tf.keras.layers.Dense(8, activation="swish")(H) 
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

### 모델 구조 확인

In [15]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_3 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


## 2-5. 데이터로 모델 학습(FIT)

In [ ]:
model.fit(inde_var, de_var, epochs=100)

## 2-6. 모델 이용하여 예측

In [19]:
print(model.predict(inde_var[0:5]))
print(de_var[0:5])

[[9.8757553e-01 1.2424393e-02 4.7411324e-09]
 [9.7550088e-01 2.4499122e-02 3.5009396e-08]
 [9.7907019e-01 2.0929830e-02 2.5220499e-08]
 [9.6845567e-01 3.1544257e-02 7.6954443e-08]
 [9.8783910e-01 1.2160869e-02 4.6588573e-09]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


# 1. 데이터 타입 조정 TIP
https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris2.csv 

1. datatype 변환
* 변수(칼럼) 데이터 타입 확인) <데이터>.dtypes
* 변수를 범주형으로 변경: <데이터>[칼럼명].astype('category')
* 변수를 수치형으로 변경: <데이터>[칼럼명].astype('int, float, etc.')

2. NA값 처리
* NA 개수 체크: <데이터>.isna().sum()
* NA값 채우기: <데이터>[칼럼명].fillna(<임의숫자>)

## 실습1.

In [20]:
import pandas as pd

In [21]:
file_route = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris2.csv'
iris = pd.read_csv(file_route)
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종
0   5.1  3.5    1.4   0.2   0
1   4.9  3.0    1.4   0.2   0
2   4.7  3.2    1.3   0.2   0
3   4.6  3.1    1.5   0.2   0
4   5.0  3.6    1.4   0.2   0

In [22]:
# 원핫인코딩
encoding = pd.get_dummies(iris)
encoding.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종
0   5.1  3.5    1.4   0.2   0
1   4.9  3.0    1.4   0.2   0
2   4.7  3.2    1.3   0.2   0
3   4.6  3.1    1.5   0.2   0
4   5.0  3.6    1.4   0.2   0

이렇게 하면 출력이 안 바뀜, why? 기존 데이터타입이 범주형(category / object)이 아니어서.
-> datatype 체크해보자

In [23]:
print(iris.dtypes)

꽃잎길이     float64
꽃잎폭      float64
꽃받침길이    float64
꽃받침폭     float64
품종         int64
dtype: object


In [24]:
# 품종's datatype 변환
iris['품종'] = iris['품종'].astype('category')
print(iris.dtypes)

꽃잎길이      float64
꽃잎폭       float64
꽃받침길이     float64
꽃받침폭      float64
품종       category
dtype: object


In [25]:
# 다시 원핫인코딩
encoding = pd.get_dummies(iris)
encoding.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_0  품종_1  품종_2
0   5.1  3.5    1.4   0.2     1     0     0
1   4.9  3.0    1.4   0.2     1     0     0
2   4.7  3.2    1.3   0.2     1     0     0
3   4.6  3.1    1.5   0.2     1     0     0
4   5.0  3.6    1.4   0.2     1     0     0

## 실습2.

In [26]:
# NA값 체크
iris.isna().sum()

꽃잎길이     0
꽃잎폭      1
꽃받침길이    0
꽃받침폭     0
품종       0
dtype: int64

In [27]:
iris.tail() # 꽃잎폭 맨 아래가 NaN

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭 품종
145   6.7  3.0    5.2   2.3  2
146   6.3  2.5    5.0   1.9  2
147   6.5  3.0    5.2   2.0  2
148   6.2  3.4    5.4   2.3  2
149   5.9  NaN    5.1   1.8  2

### NaN 해결법 3가지
1. 액셀 같은 편집 도구로 행 편집
2. NaN 대신 new 값 넣기
3. NaN이 포함된 행 삭제

In [29]:
# NaN 값에 꽃잎폭의 평균값 대입
mean = iris['꽃잎폭'].mean()
iris['꽃잎폭'] = iris['꽃잎폭'].fillna(mean)
iris.tail()

꽃잎길이       꽃잎폭  꽃받침길이  꽃받침폭 품종
145   6.7  3.000000    5.2   2.3  2
146   6.3  2.500000    5.0   1.9  2
147   6.5  3.000000    5.2   2.0  2
148   6.2  3.400000    5.4   2.3  2
149   5.9  3.054362    5.1   1.8  2

# 2. 모델 TIP

* 모델의 구조는 내가 지정하는 것

## +
구조를 복잡하게 만들어서 학습을 제대로 시키기만 한다면
준비한 데이터로 더욱 정확한 모델을 만들 수 있음

## -
1. 복잡하면 제대로 학습시키기 어려워짐 <br>
2. 준비된 데이터 외의 현실의 데이터에 대해서도 동일한 결과를 내는 모델이어야 함

## 학습이 잘 되는 모델
* 사용할 레이어
- tf.keras.layers.BatchNormalization(): Dense() & Activation() 사이에 적음
- tf.keras.layers.Activation('swish')
* 데이터 <br>
https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv
https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv



In [30]:
import tensorflow as tf
import pandas as pd

In [31]:
file_route = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
boston = pd.read_csv(file_route)

inde_var = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
de_var = boston[['medv']]

print(inde_var.shape, de_var.shape)

(506, 13) (506, 1)


In [35]:
X = tf.keras.layers.Input(shape=[13])

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [36]:
model.fit(inde_var, de_var, epochs=1000, verbose=0)
model.fit(inde_var, de_var, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 4ms/step - loss: 12.6937
Epoch 2/10
16/16 [==============================] - 0s 4ms/step - loss: 10.4244
Epoch 3/10
16/16 [==============================] - 0s 3ms/step - loss: 10.2968
Epoch 4/10
16/16 [==============================] - 0s 4ms/step - loss: 12.2966
Epoch 5/10
16/16 [==============================] - 0s 4ms/step - loss: 9.5277
Epoch 6/10
16/16 [==============================] - 0s 4ms/step - loss: 9.8348
Epoch 7/10
16/16 [==============================] - 0s 3ms/step - loss: 12.5371
Epoch 8/10
16/16 [==============================] - 0s 3ms/step - loss: 10.9022
Epoch 9/10
16/16 [==============================] - 0s 3ms/step - loss: 12.2225
Epoch 10/10
16/16 [==============================] - 0s 4ms/step - loss: 10.1978


### 분류 모델도 똑같이~~