In [1]:
from __future__ import print_function
import torch

### 초기화 되지 않은 행렬 선언

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


### 무작위 행렬 초기화

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5931, 0.0720, 0.7804],
        [0.9276, 0.0675, 0.5670],
        [0.5164, 0.5849, 0.6651],
        [0.1267, 0.8331, 0.8119],
        [0.6237, 0.9800, 0.0475]])


### 영행렬

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


### 텐서 직접 생성

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* 메소드는 크기를 받습니다
print(x)

x = torch.randn_like(x, dtype=torch.float)    # dtype을 오버라이드(Override) 합니다!
print(x)                                      # 결과는 동일한 크기를 갖습니다

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.3631, -0.2239, -0.4806],
        [ 2.0957, -1.6409, -0.2991],
        [ 1.6011,  0.1253, -1.3804],
        [ 1.1848,  0.7690,  0.4696],
        [-0.6696,  1.4068, -0.8509]])


In [7]:
print(x.size())

torch.Size([5, 3])


### 텐서 덧셈

In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.1390,  0.0221,  0.1776],
        [ 2.8064, -0.6573,  0.0534],
        [ 2.0550,  0.5958, -0.7543],
        [ 1.9653,  1.4300,  1.3211],
        [-0.1474,  1.7361, -0.0095]])


In [9]:
print(torch.add(x, y))

tensor([[ 0.1390,  0.0221,  0.1776],
        [ 2.8064, -0.6573,  0.0534],
        [ 2.0550,  0.5958, -0.7543],
        [ 1.9653,  1.4300,  1.3211],
        [-0.1474,  1.7361, -0.0095]])


In [10]:
print(x[:, 1])

tensor([-0.2239, -1.6409,  0.1253,  0.7690,  1.4068])


### 크기변경

In [11]:
# tensor의 크기(size)나 모양(shape)을 변경하고 싶다면 torch.view 를 사용합니다:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # -1은 다른 차원에서 유추합니다.
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [12]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.0694])
0.06939966976642609


In [13]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [14]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [15]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [16]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [17]:
# 이 코드는 CUDA가 사용 가능한 환경에서만 실행합니다.
# ``torch.device`` 를 사용하여 tensor를 GPU 안팎으로 이동해보겠습니다.
# if torch.cuda.is_available():
device = torch.device("cuda")          # CUDA 장치 객체(device object)로
y = torch.ones_like(x, device=device)  # GPU 상에 직접적으로 tensor를 생성하거나
x = x.to(device)                       # ``.to("cuda")`` 를 사용하면 됩니다.
z = x + y
print(z)
print(z.to("cpu", torch.double))       # ``.to`` 는 dtype도 함께 변경합니다!

tensor([1.0694], device='cuda:0')
tensor([1.0694], dtype=torch.float64)
