In [1]:
import numpy as np
import tensorflow as tf

In [2]:
print(tf.__version__)

2.4.1


In [10]:
# 텐서 객체
#  타입 Type: string, float32, float16,int32,int8 등
#  형상 Shape: 0,1,2 차원 등의 데이터 차원
#  축 Rank: 차원의 개수

## 상수 텐서

In [6]:
# 2 와 3 이라는 값을 가지는 1차원 텐서 생성
b = tf.constant([2,3]) 
print(tf.rank(b))
print(b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)


In [7]:
# 2 차원 상수 텐서
c = tf.constant([[2,3],[6,7]])
print(tf.rank(c)) # shape 는 2 X 2 텐서이므로
print(c)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[2 3]
 [6 7]], shape=(2, 2), dtype=int32)


In [9]:
# 상수로 문자열을 넣어본다
d = tf.constant(['world'])
print(tf.rank(d)) # 1차원 텐서에 값이 하나 shape = (1,)
print(d)  # 데이터 타입 string

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([b'world'], shape=(1,), dtype=string)


## 난수 생성

In [11]:
rand = tf.random.uniform([1],0,1) # shape 을 1로 가지는, 0 부터 1 까지  랜덤값
print(rand.shape)
print(rand)

(1,)
tf.Tensor([0.383664], shape=(1,), dtype=float32)


In [12]:
rand2 = tf.random.normal([1,2],0,1) # 정규분포 normal 로 평균 mean 값이 0.0 이고 stddev=1.0 으로 지정
print(rand2.shape)
print(rand2)

(1, 2)
tf.Tensor([[-0.34767434 -0.133413  ]], shape=(1, 2), dtype=float32)


In [13]:
rand3 = tf.random.normal(shape=(3,2),mean=0,stddev=1)
print(rand3.shape)
print(rand3)

(3, 2)
tf.Tensor(
[[ 0.2585169   0.4375243 ]
 [ 0.1149057  -0.20234229]
 [-0.22788717 -1.0669224 ]], shape=(3, 2), dtype=float32)


## 즉시 실행모드 (Eager Mode)

In [17]:
a = tf.constant(3)
b = tf.constant(2)
#
print(tf.add(a,b))
print(a+b)
# 
print(tf.subtract(a,b))
print(a-b)
# 
print(tf.multiply(a,b))
print(a*b)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


## 텐서플로우 <-> 넘파이
```py
numpy()
tf.convet_to_tensor()
```

In [24]:
# a=3, b=2 
c = tf.add(a,b).numpy() # 5
print(c)
print(type(c))

5
<class 'numpy.int32'>


In [21]:
# numpy 타입으로 5 값을 np.square 로 (5 의 square 값) 25 
# float32 타입으로 변환하므로 25.0 
c_square = np.square(c,dtype= np.float32)
c_tensor = tf.convert_to_tensor(c_square)

print(c_tensor)
print(type(c_tensor)) # 즉시실행모드 EagerMode 

tf.Tensor(25.0, shape=(), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


## 넘파이처럼 사용

In [26]:
t = tf.constant([[1.,2.,3.],[4.,5.,6.]])
print(t)
print(t.dtype)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
<dtype: 'float32'>


In [27]:
# 텐서 슬라이싱 2,3 
# 첫번째 차원 전부, 두번째 차원 인덱스 1부터 
# 0 번째인 1,4 날라감 
print(t[:,1:]) # [[2.,3.],[5.,6.]]

tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)


In [28]:
### ... : 알아서, 1 : 첫번째 해당하는 것만 (여기서는 2,5만)
t[...,1,tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [29]:
# 각 요소에 대해 
t + 10 

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [30]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [31]:
# 텐서 곱연산 2X3 * 3X2 
t @ tf.transpose(t) 

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [35]:
# 연산시 텐서의 타입을 맞춰줘야 한다.
# 타입 변환에는 tf.cast() 를 사용한다. 
a = tf.constant(2)
print(a)
b = tf.constant(2.0)
print(b)

try:
    a + b
except Exception as e: # 텐서 타입이 맞지 않아 발생하는 오류
    print(e)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(2.0, shape=(), dtype=float32)
cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2]


In [37]:
try:
    tf.constant(2.) + tf.constant(30.,dtype=tf.float64) # 타입이 float32, float64 로 서로 다르다
except Exception as e:
    print(e)

cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2]


In [38]:
t = tf.constant(30.,dtype = tf.float64)
t2 = tf.constant(4.)
print(t2 + tf.cast(t,tf.float32))

tf.Tensor(34.0, shape=(), dtype=float32)


## AutoGraph 
텐서플로우가 작업을 더 빠르게 동작하기 위한 방법으로 Graph 로 만들어 연산을 진행
`tf.Graph`

In [ ]:
# @tf.function
# 자동으로 그래프를 생성 (Auto Graph)
# 그래프로 변환하여 사용 -> GPU 연산 가능
# 파이썬으로 구성된 함수를 텐서플로우의 그래프 형태로 다루고 싶을 때 사용가능
# 원본 함수가 필요하다면 (tf.function).python_function()

In [40]:
# 텐서 형태로 결과를 리턴해준다. 
@tf.function
def my_function(x):
    return x**2 - 10*x +3

print(my_function(2))
print(my_function(tf.constant(2)))

tf.Tensor(-13, shape=(), dtype=int32)
tf.Tensor(-13, shape=(), dtype=int32)
